/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mageddo.commons.jdbc;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
